<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class PathogensFactory extends Factory
{
    protected static $availablePathogens;

    public function definition(): array
    {
        if (is_null(self::$availablePathogens)) {
            self::$availablePathogens = collect([
                [
                    'ncbi_tax_id' => 234,
                    'species' => 'Brucella abortus',
                    'genus' => 'Brucella',
                    'family' => 'Brucellaceae',
                    'order' => 'Rhizobiales',
                    'class' => 'Alphaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 78533,
                    'species' => 'Rickettsia africae',
                    'genus' => 'Rickettsia',
                    'family' => 'Rickettsiaceae',
                    'order' => 'Rickettsiales',
                    'class' => 'Alphaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 775,
                    'species' => 'Anaplasma marginale',
                    'genus' => 'Anaplasma',
                    'family' => 'Anaplasmataceae',
                    'order' => 'Rickettsiales',
                    'class' => 'Alphaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 234,
                    'species' => 'Brucella spp.',
                    'genus' => 'Brucella',
                    'family' => 'Brucellaceae',
                    'order' => 'Rhizobiales',
                    'class' => 'Alphaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 58632,
                    'species' => 'Babesia bovis',
                    'genus' => 'Babesia',
                    'family' => 'Babesiidae',
                    'order' => 'Piroplasmida',
                    'class' => 'Aconoidasida',
                    'phylum' => 'Apicomplexa',
                    'kingdom' => 'Chromista',
                    'domain' => 'Eukaryota',
                ],
                [
                    'ncbi_tax_id' => 5874,
                    'species' => 'Theileria parva',
                    'genus' => 'Theileria',
                    'family' => 'Theileriidae',
                    'order' => 'Piroplasmida',
                    'class' => 'Aconoidasida',
                    'phylum' => 'Apicomplexa',
                    'kingdom' => 'Chromista',
                    'domain' => 'Eukaryota',
                ],
                [
                    'ncbi_tax_id' => 562,
                    'species' => 'Escherichia coli',
                    'genus' => 'Escherichia',
                    'family' => 'Enterobacteriaceae',
                    'order' => 'Enterobacterales',
                    'class' => 'Gammaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 28901,
                    'species' => 'Salmonella enterica',
                    'genus' => 'Salmonella',
                    'family' => 'Enterobacteriaceae',
                    'order' => 'Enterobacterales',
                    'class' => 'Gammaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1764,
                    'species' => 'Mycobacterium bovis',
                    'genus' => 'Mycobacterium',
                    'family' => 'Mycobacteriaceae',
                    'order' => 'Actinomycetales',
                    'class' => 'Actinobacteria',
                    'phylum' => 'Actinobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 173,
                    'species' => 'Leptospira interrogans',
                    'genus' => 'Leptospira',
                    'family' => 'Leptospiraceae',
                    'order' => 'Leptospirales',
                    'class' => 'Spirochaetia',
                    'phylum' => 'Spirochaetes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 777,
                    'species' => 'Coxiella burnetii',
                    'genus' => 'Coxiella',
                    'family' => 'Coxiellaceae',
                    'order' => 'Legionellales',
                    'class' => 'Gammaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 83558,
                    'species' => 'Chlamydia psittaci',
                    'genus' => 'Chlamydia',
                    'family' => 'Chlamydiaceae',
                    'order' => 'Chlamydiales',
                    'class' => 'Chlamydiia',
                    'phylum' => 'Chlamydiae',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 2092,
                    'species' => 'Mycoplasma bovis',
                    'genus' => 'Mycoplasma',
                    'family' => 'Mycoplasmataceae',
                    'order' => 'Mycoplasmatales',
                    'class' => 'Mollicutes',
                    'phylum' => 'Tenericutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 197,
                    'species' => 'Campylobacter jejuni',
                    'genus' => 'Campylobacter',
                    'family' => 'Campylobacteraceae',
                    'order' => 'Campylobacterales',
                    'class' => 'Epsilonproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1639,
                    'species' => 'Listeria monocytogenes',
                    'genus' => 'Listeria',
                    'family' => 'Listeriaceae',
                    'order' => 'Bacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1280,
                    'species' => 'Staphylococcus aureus',
                    'genus' => 'Staphylococcus',
                    'family' => 'Staphylococcaceae',
                    'order' => 'Bacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1311,
                    'species' => 'Streptococcus agalactiae',
                    'genus' => 'Streptococcus',
                    'family' => 'Streptococcaceae',
                    'order' => 'Lactobacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 287,
                    'species' => 'Pseudomonas aeruginosa',
                    'genus' => 'Pseudomonas',
                    'family' => 'Pseudomonadaceae',
                    'order' => 'Pseudomonadales',
                    'class' => 'Gammaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 573,
                    'species' => 'Klebsiella pneumoniae',
                    'genus' => 'Klebsiella',
                    'family' => 'Enterobacteriaceae',
                    'order' => 'Enterobacterales',
                    'class' => 'Gammaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 584,
                    'species' => 'Proteus mirabilis',
                    'genus' => 'Proteus',
                    'family' => 'Enterobacteriaceae',
                    'order' => 'Enterobacterales',
                    'class' => 'Gammaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1351,
                    'species' => 'Enterococcus faecalis',
                    'genus' => 'Enterococcus',
                    'family' => 'Enterococcaceae',
                    'order' => 'Lactobacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1502,
                    'species' => 'Clostridium perfringens',
                    'genus' => 'Clostridium',
                    'family' => 'Clostridiaceae',
                    'order' => 'Clostridiales',
                    'class' => 'Clostridia',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1392,
                    'species' => 'Bacillus anthracis',
                    'genus' => 'Bacillus',
                    'family' => 'Bacillaceae',
                    'order' => 'Bacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 632,
                    'species' => 'Yersinia pestis',
                    'genus' => 'Yersinia',
                    'family' => 'Yersiniaceae',
                    'order' => 'Enterobacterales',
                    'class' => 'Gammaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 263,
                    'species' => 'Francisella tularensis',
                    'genus' => 'Francisella',
                    'family' => 'Francisellaceae',
                    'order' => 'Thiotrichales',
                    'class' => 'Gammaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1124,
                    'species' => 'Bordetella pertussis',
                    'genus' => 'Bordetella',
                    'family' => 'Alcaligenaceae',
                    'order' => 'Burkholderiales',
                    'class' => 'Betaproteobacteria',
                    'phylum' => 'Proteobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1423,
                    'species' => 'Bacillus cereus',
                    'genus' => 'Bacillus',
                    'family' => 'Bacillaceae',
                    'order' => 'Bacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1282,
                    'species' => 'Staphylococcus epidermidis',
                    'genus' => 'Staphylococcus',
                    'family' => 'Staphylococcaceae',
                    'order' => 'Bacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1314,
                    'species' => 'Streptococcus pneumoniae',
                    'genus' => 'Streptococcus',
                    'family' => 'Streptococcaceae',
                    'order' => 'Lactobacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1313,
                    'species' => 'Streptococcus pyogenes',
                    'genus' => 'Streptococcus',
                    'family' => 'Streptococcaceae',
                    'order' => 'Lactobacillales',
                    'class' => 'Bacilli',
                    'phylum' => 'Firmicutes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1763,
                    'species' => 'Mycobacterium tuberculosis',
                    'genus' => 'Mycobacterium',
                    'family' => 'Mycobacteriaceae',
                    'order' => 'Actinomycetales',
                    'class' => 'Actinobacteria',
                    'phylum' => 'Actinobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 1768,
                    'species' => 'Mycobacterium avium',
                    'genus' => 'Mycobacterium',
                    'family' => 'Mycobacteriaceae',
                    'order' => 'Actinomycetales',
                    'class' => 'Actinobacteria',
                    'phylum' => 'Actinobacteria',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 174,
                    'species' => 'Leptospira borgpetersenii',
                    'genus' => 'Leptospira',
                    'family' => 'Leptospiraceae',
                    'order' => 'Leptospirales',
                    'class' => 'Spirochaetia',
                    'phylum' => 'Spirochaetes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 175,
                    'species' => 'Leptospira kirschneri',
                    'genus' => 'Leptospira',
                    'family' => 'Leptospiraceae',
                    'order' => 'Leptospirales',
                    'class' => 'Spirochaetia',
                    'phylum' => 'Spirochaetes',
                    'kingdom' => 'Bacteria',
                    'domain' => 'Bacteria',
                ],
                [
                    'ncbi_tax_id' => 58633,
                    'species' => 'Babesia bigemina',
                    'genus' => 'Babesia',
                    'family' => 'Babesiidae',
                    'order' => 'Piroplasmida',
                    'class' => 'Aconoidasida',
                    'phylum' => 'Apicomplexa',
                    'kingdom' => 'Chromista',
                    'domain' => 'Eukaryota',
                ],
                [
                    'ncbi_tax_id' => 5875,
                    'species' => 'Theileria annulata',
                    'genus' => 'Theileria',
                    'family' => 'Theileriidae',
                    'order' => 'Piroplasmida',
                    'class' => 'Aconoidasida',
                    'phylum' => 'Apicomplexa',
                    'kingdom' => 'Chromista',
                    'domain' => 'Eukaryota',
                ],
                // Viruses
                [
                    'ncbi_tax_id' => 11620,
                    'species' => 'Foot-and-mouth disease virus',
                    'genus' => 'Aphthovirus',
                    'family' => 'Picornaviridae',
                    'order' => 'Picornavirales',
                    'class' => 'Pisoniviricetes',
                    'phylum' => 'Pisuviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11053,
                    'species' => 'Rift Valley fever virus',
                    'genus' => 'Phlebovirus',
                    'family' => 'Phenuiviridae',
                    'order' => 'Bunyavirales',
                    'class' => 'Ellioviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11060,
                    'species' => 'Crimean-Congo hemorrhagic fever virus',
                    'genus' => 'Orthonairovirus',
                    'family' => 'Nairoviridae',
                    'order' => 'Bunyavirales',
                    'class' => 'Ellioviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11070,
                    'species' => 'West Nile virus',
                    'genus' => 'Flavivirus',
                    'family' => 'Flaviviridae',
                    'order' => 'Amarillovirales',
                    'class' => 'Flasuviricetes',
                    'phylum' => 'Kitrinoviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11069,
                    'species' => 'Dengue virus',
                    'genus' => 'Flavivirus',
                    'family' => 'Flaviviridae',
                    'order' => 'Amarillovirales',
                    'class' => 'Flasuviricetes',
                    'phylum' => 'Kitrinoviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11072,
                    'species' => 'Yellow fever virus',
                    'genus' => 'Flavivirus',
                    'family' => 'Flaviviridae',
                    'order' => 'Amarillovirales',
                    'class' => 'Flasuviricetes',
                    'phylum' => 'Kitrinoviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11075,
                    'species' => 'Zika virus',
                    'genus' => 'Flavivirus',
                    'family' => 'Flaviviridae',
                    'order' => 'Amarillovirales',
                    'class' => 'Flasuviricetes',
                    'phylum' => 'Kitrinoviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11103,
                    'species' => 'Rabies virus',
                    'genus' => 'Lyssavirus',
                    'family' => 'Rhabdoviridae',
                    'order' => 'Mononegavirales',
                    'class' => 'Monjiviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11118,
                    'species' => 'Influenza A virus',
                    'genus' => 'Alphainfluenzavirus',
                    'family' => 'Orthomyxoviridae',
                    'order' => 'Articulavirales',
                    'class' => 'Insthoviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11120,
                    'species' => 'Influenza B virus',
                    'genus' => 'Betainfluenzavirus',
                    'family' => 'Orthomyxoviridae',
                    'order' => 'Articulavirales',
                    'class' => 'Insthoviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11121,
                    'species' => 'Influenza C virus',
                    'genus' => 'Gammainfluenzavirus',
                    'family' => 'Orthomyxoviridae',
                    'order' => 'Articulavirales',
                    'class' => 'Insthoviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11124,
                    'species' => 'Measles virus',
                    'genus' => 'Morbillivirus',
                    'family' => 'Paramyxoviridae',
                    'order' => 'Mononegavirales',
                    'class' => 'Monjiviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11125,
                    'species' => 'Mumps virus',
                    'genus' => 'Rubulavirus',
                    'family' => 'Paramyxoviridae',
                    'order' => 'Mononegavirales',
                    'class' => 'Monjiviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11126,
                    'species' => 'Respiratory syncytial virus',
                    'genus' => 'Orthopneumovirus',
                    'family' => 'Pneumoviridae',
                    'order' => 'Mononegavirales',
                    'class' => 'Monjiviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11127,
                    'species' => 'Parainfluenza virus 1',
                    'genus' => 'Respirovirus',
                    'family' => 'Paramyxoviridae',
                    'order' => 'Mononegavirales',
                    'class' => 'Monjiviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11128,
                    'species' => 'Parainfluenza virus 3',
                    'genus' => 'Respirovirus',
                    'family' => 'Paramyxoviridae',
                    'order' => 'Mononegavirales',
                    'class' => 'Monjiviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11129,
                    'species' => 'Sendai virus',
                    'genus' => 'Respirovirus',
                    'family' => 'Paramyxoviridae',
                    'order' => 'Mononegavirales',
                    'class' => 'Monjiviricetes',
                    'phylum' => 'Negarnaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11135,
                    'species' => 'Rotavirus A',
                    'genus' => 'Rotavirus',
                    'family' => 'Reoviridae',
                    'order' => 'Reovirales',
                    'class' => 'Resentoviricetes',
                    'phylum' => 'Duplornaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11136,
                    'species' => 'Rotavirus B',
                    'genus' => 'Rotavirus',
                    'family' => 'Reoviridae',
                    'order' => 'Reovirales',
                    'class' => 'Resentoviricetes',
                    'phylum' => 'Duplornaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11137,
                    'species' => 'Rotavirus C',
                    'genus' => 'Rotavirus',
                    'family' => 'Reoviridae',
                    'order' => 'Reovirales',
                    'class' => 'Resentoviricetes',
                    'phylum' => 'Duplornaviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11138,
                    'species' => 'Norwalk virus',
                    'genus' => 'Norovirus',
                    'family' => 'Caliciviridae',
                    'order' => 'Picornavirales',
                    'class' => 'Pisoniviricetes',
                    'phylum' => 'Pisuviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11139,
                    'species' => 'Sapovirus',
                    'genus' => 'Sapovirus',
                    'family' => 'Caliciviridae',
                    'order' => 'Picornavirales',
                    'class' => 'Pisoniviricetes',
                    'phylum' => 'Pisuviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11140,
                    'species' => 'Astrovirus',
                    'genus' => 'Mamastrovirus',
                    'family' => 'Astroviridae',
                    'order' => 'Stellavirales',
                    'class' => 'Stelpaviricetes',
                    'phylum' => 'Pisuviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11141,
                    'species' => 'Adenovirus C',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11142,
                    'species' => 'Adenovirus D',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11143,
                    'species' => 'Adenovirus E',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11144,
                    'species' => 'Adenovirus F',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11145,
                    'species' => 'Adenovirus G',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11146,
                    'species' => 'Adenovirus H',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11147,
                    'species' => 'Adenovirus I',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11148,
                    'species' => 'Adenovirus J',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11149,
                    'species' => 'Adenovirus K',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11150,
                    'species' => 'Adenovirus L',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11151,
                    'species' => 'Adenovirus M',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11152,
                    'species' => 'Adenovirus N',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11153,
                    'species' => 'Adenovirus O',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11154,
                    'species' => 'Adenovirus P',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11155,
                    'species' => 'Adenovirus Q',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11156,
                    'species' => 'Adenovirus R',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11157,
                    'species' => 'Adenovirus S',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11158,
                    'species' => 'Adenovirus T',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11159,
                    'species' => 'Adenovirus U',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11160,
                    'species' => 'Adenovirus V',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11161,
                    'species' => 'Adenovirus W',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11162,
                    'species' => 'Adenovirus X',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11163,
                    'species' => 'Adenovirus Y',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
                [
                    'ncbi_tax_id' => 11164,
                    'species' => 'Adenovirus Z',
                    'genus' => 'Mastadenovirus',
                    'family' => 'Adenoviridae',
                    'order' => 'Rowavirales',
                    'class' => 'Tectiliviricetes',
                    'phylum' => 'Uroviricota',
                    'kingdom' => 'Orthornavirae',
                    'domain' => 'Riboviria',
                ],
            ])->shuffle(); // Randomize the order once
        }

        // Pop one unique pathogen off the collection
        $item = self::$availablePathogens->pop();

        if (! $item) {
            throw new \Exception('No more unique pathogens available in factory.');
        }

        return [
            'ncbi_tax_id' => $item['ncbi_tax_id'],
            'species' => $item['species'],
            'genus' => $item['genus'],
            'family' => $item['family'],
            'order' => $item['order'],
            'class' => $item['class'],
            'phylum' => $item['phylum'],
            'kingdom' => $item['kingdom'],
            'domain' => $item['domain'],
        ];
    }
}
